CREATE TABLE Countries
    (
      id INT IDENTITY(1, 1) NOT NULL
                     PRIMARY KEY ,
      CountryName NVARCHAR(128) NOT NULL,
      CountryNameEng NVARCHAR(128) NOT NULL
    );

	GO

SET IDENTITY_INSERT Countries OFF;   
Insert Into Countries (CountryNameEng, CountryName) values 
('Uganda','אוגנדה'),
('Uzbekistan', 'אוזבקיסטן'),
('Austria', 'אוסטריה'),
('Australia', 'אוסטרליה'),
('Ukraine', 'אוקראינה'),
('Uruguay', 'אורוגוואי'),
('Azerbaijan', 'אזרבייג''ן'),
('United Arab Emirates', 'איחוד האמירויות הערביות'),
('Italy', 'איטליה'),
('Ashmore and Cartier Islands', 'איי אשמור וקרטייה'),
('The Bahamas', 'איי בהאמה'),
('South Georgia and the South Sandwich Islands', 'איי ג''ורג''יה הדרומית ואיי סנדוויץ'' הדרומיים'),
('Virgin Islands', 'איי הבתולה'),
('British Virgin Islands', 'איי הבתולה הבריטיים'),
('Turks and Caicos Islands', 'איי טרקס וקייקוס'),
('Northern Mariana Islands', 'איי מריאנה הצפוניים'),
('Marshall Islands', 'איי מרשל'),
('Paracel Islands', 'איי פאראסל'),
('Faroe Islands', 'איי פארו'),
('Falkland Islands', 'איי פוקלנד'),
('Cook Islands', 'איי קוק'),
('Cocos (Keeling) Islands', 'איי קוקוס'),
('Cayman Islands', 'איי קיימן'),
('Solomon Islands', 'איי שלמה'),
('Indonesia', 'אינדונזיה'),
('Iceland', 'איסלנד'),
('Iran', 'איראן'),
('Ireland', 'אירלנד'),
('El Salvador', 'אל סלוודור'),
('Albania', 'אלבניה'),
('Algeria', 'אלג''יריה'),
('Anguilla', 'אנגווילה'),
('Angola', 'אנגולה'),
('Andorra', 'אנדורה'),
('Antarctica', 'אנטארקטיקה'),
('Antigua and Barbuda', 'אנטיגואה וברבודה'),
('Estonia', 'אסטוניה'),
('Afghanistan', 'אפגניסטן'),
('Ecuador', 'אקוודור'),
('Akrotiri and Dhekelia', 'אקרוטירי ודקליה'),
('Argentina', 'ארגנטינה'),
('Aruba', 'ארובה (טריטוריה)'),
('Eritrea', 'אריתריאה'),
('Armenia', 'ארמניה'),
('United States', 'ארצות הברית'),
('Ethiopia', 'אתיופיה'),
('Bhutan', 'בהוטן'),
('Bouvet Island', 'בובה (אי)'),
('Botswana', 'בוטסואנה'),
('Bulgaria', 'בולגריה'),
('Bolivia', 'בוליביה'),
('Bosnia and Herzegovina', 'בוסניה והרצגובינה'),
('Burundi', 'בורונדי'),
('Burkina Faso', 'בורקינה פאסו'),
('Bahrain', 'בחריין'),
('Belarus', 'בלארוס'),
('Belgium', 'בלגיה'),
('Belize', 'בליז'),
('Bangladesh', 'בנגלדש'),
('Benin', 'בנין'),
('Barbados', 'ברבדוס'),
('Brunei', 'ברוניי'),
('Brazil', 'ברזיל'),
('Bermuda', 'ברמודה'),
('Georgia', 'ג''ורג''יה (פירושונים)'),
('Djibouti', 'ג''יבוטי'),
('Jamaica', 'ג''מייקה'),
('Jersey', 'ג''רזי'),
('Ghana', 'גאנה'),
('Gabon', 'גבון'),
('Guatemala', 'גואטמלה'),
('Guam', 'גואם'),
('Gibraltar', 'גיברלטר'),
('Guinea', 'גינאה'),
('Guinea-Bissau', 'גינאה ביסאו'),
('Equatorial Guinea', 'גינאה המשוונית'),
('The Gambia', 'גמביה'),
('Greenland', 'גרינלנד'),
('Germany', 'גרמניה'),
('Grenada', 'גרנדה'),
('Guernsey', 'גרנזי'),
('Dominica', 'דומיניקה'),
('Denmark', 'דנמרק'),
('South Africa', 'דרום אפריקה'),
('South Sudan', 'דרום סודאן'),
('Howland Island', 'האולנד'),
('Heard Island and McDonald Islands', 'האי הרד ואיי מקדונלד'),
('Wake Island', 'האי וייק'),
('Isle of Man', 'האי מאן'),
('Norfolk Island', 'האי נורפוק'),
('European Union ','האיחוד האירופי'),
('Haiti', 'האיטי'),
('Maldives', 'האיים המלדיביים'),
('French Southern and Antarctic Lands', 'הארצות הדרומיות והאנטארקטיות של צרפת'),
('India', 'הודו'),
('Netherlands', 'הולנד'),
('Hong Kong', 'הונג קונג'),
('Hungary', 'הונגריה'),
('Honduras', 'הונדורס'),
('British Indian Ocean Territory', 'הטריטוריה הבריטית באוקיינוס ההודי'),
('Pacific Remote Islands Marine National Monument', 'המונומנט הימי הלאומי באיים הפסיפיים המרוחקים'),
('United Kingdom', 'הממלכה המאוחדת'),
('Philippines', 'הפיליפינים'),
('Dominican Republic', 'הרפובליקה הדומיניקנית'),
('Democratic Republic of the Congo', 'הרפובליקה הדמוקרטית של קונגו'),
('Central African Republic', 'הרפובליקה המרכז-אפריקאית'),
('China', 'הרפובליקה העממית של סין'),
('Republic of the Congo', 'הרפובליקה של קונגו'),
('Wallis and Futuna', 'ואליס ופוטונה'),
('Vietnam', 'וייטנאם'),
('Vanuatu', 'ונואטו'),
('Venezuela', 'ונצואלה'),
('Zimbabwe', 'זימבבואה'),
('Zambia', 'זמביה'),
('Christmas Island', 'חג המולד (אי)'),
('Ivory Coast', 'חוף השנהב'),
('Taiwan', 'טאיוואן'),
('Tajikistan', 'טג''יקיסטן'),
('Tuvalu', 'טובאלו'),
('Togo', 'טוגו'),
('Tonga', 'טונגה'),
('Tokelau', 'טוקלאו'),
('Turkey', 'טורקיה'),
('Turkmenistan', 'טורקמניסטן'),
('Tanzania', 'טנזניה'),
('Coral Sea Islands', 'טריטוריית איי ים האלמוגים'),
('Trinidad and Tobago', 'טרינידד וטובגו'),
('Jan Mayen', 'יאן מאיין'),
('West Bank', 'יהודה ושומרון'),
('Greece', 'יוון'),
('Japan', 'יפן'),
('Jordan', 'ירדן'),
('Israel', 'ישראל'),
('Kuwait', 'כווית'),
('Cape Verde', 'כף ורדה'),
('Laos', 'לאוס'),
('Lebanon', 'לבנון'),
('Libya', 'לוב'),
('Luxembourg', 'לוקסמבורג'),
('Latvia', 'לטביה'),
('Liberia', 'ליבריה'),
('Lithuania', 'ליטא'),
('Liechtenstein', 'ליכטנשטיין'),
('Lesotho', 'לסוטו'),
('Mauritania', 'מאוריטניה'),
('Mauritius', 'מאוריציוס'),
('Mali', 'מאלי'),
('Madagascar', 'מדגסקר'),
('Mozambique', 'מוזמביק'),
('Moldova', 'מולדובה'),
('Monaco', 'מונאקו'),
('Mongolia', 'מונגוליה'),
('Montenegro', 'מונטנגרו'),
('Montserrat', 'מונטסראט'),
('East Timor', 'מזרח טימור'),
('Burma', 'מיאנמר'),
('Federated States of Micronesia', 'מיקרונזיה'),
('Malawi', 'מלאווי'),
('Malaysia', 'מלזיה'),
('Malta', 'מלטה'),
('Egypt', 'מצרים'),
('Macau', 'מקאו'),
('Macedonia', 'מקדוניה'),
('Mexico', 'מקסיקו'),
('Morocco', 'מרוקו'),
('Nauru', 'נאורו'),
('Navassa Island', 'נבאסה'),
('Norway', 'נורבגיה'),
('Nigeria', 'ניגריה'),
('New Zealand', 'ניו זילנד'),
('Niue', 'ניואה'),
('Niger', 'ניז''ר'),
('Nicaragua', 'ניקרגואה'),
('Namibia', 'נמיביה'),
('Nepal', 'נפאל'),
('São Tomé and Príncipe', 'סאו טומה ופרינסיפה'),
('Svalbard', 'סבאלברד'),
('Western Sahara', 'סהרה המערבית'),
('Sudan', 'סודאן'),
('Swaziland', 'סווזילנד'),
('Somalia', 'סומליה'),
('Syria', 'סוריה'),
('Suriname', 'סורינאם'),
('Sierra Leone', 'סיירה לאונה'),
('Seychelles', 'סיישל'),
('Singapore', 'סינגפור'),
('Slovenia', 'סלובניה'),
('Slovakia', 'סלובקיה'),
('Samoa', 'סמואה'),
('American Samoa', 'סמואה האמריקנית'),
('Saint Barthélemy', 'סן ברתלמי'),
('Collectivity of Saint Martin', 'סן מרטן'),
('San Marino', 'סן מרינו'),
('Saint Pierre and Miquelon', 'סן פייר ומיקלון'),
('Senegal', 'סנגל'),
('Saint Vincent and the Grenadines', 'סנט וינסנט והגרנדינים'),
('Saint Lucia', 'סנט לוסיה'),
('Sint Maarten', 'סנט מארטן'),
('Saint Kitts and Nevis', 'סנט קיטס ונוויס'),
('Spain', 'ספרד'),
('Spratly Islands', 'ספרד'),
('Serbia', 'סרביה'),
('Sri Lanka', 'סרי לנקה'),
('Oman', 'עומאן'),
('Iraq', 'עיראק'),
('Saudi Arabia', 'ערב הסעודית'),
('Puerto Rico', 'פוארטו ריקו'),
('Poland', 'פולין'),
('French Polynesia', 'פולינזיה הצרפתית'),
('Portugal', 'פורטוגל'),
('Fiji', 'פיג''י'),
('Pitcairn Islands', 'פיטקרן'),
('Finland', 'פינלנד'),
('Palau', 'פלאו'),
('Panama', 'פנמה'),
('Papua New Guinea', 'פפואה גינאה החדשה'),
('Pakistan', 'פקיסטן'),
('Paraguay', 'פרגוואי'),
('Peru', 'פרו'),
('Chad', 'צ''אד'),
('Chile', 'צ''ילה'),
('Czech Republic', 'צ''כיה'),
('France', 'צרפת'),
('Cuba', 'קובה'),
('Colombia', 'קולומביה'),
('Comoros', 'קומורו'),
('Kosovo', 'קוסובו'),
('Costa Rica', 'קוסטה ריקה'),
('Curaçao', 'קוראסאו'),
('South Korea', 'קוריאה הדרומית'),
('North Korea', 'קוריאה הצפונית'),
('Kazakhstan', 'קזחסטן'),
('Qatar', 'קטאר'),
('Kyrgyzstan', 'קירגיזסטן'),
('Kiribati', 'קיריבטי'),
('New Caledonia', 'קלדוניה החדשה'),
('Clipperton Island', 'קליפרטון'),
('Cambodia', 'קמבודיה'),
('Cameroon', 'קמרון'),
('Canada', 'קנדה'),
('Kenya', 'קניה'),
('Cyprus', 'קפריסין'),
('Croatia', 'קרואטיה'),
('Holy See (Vatican City)', 'קריית הוותיקן'),
('Rwanda', 'רואנדה'),
('Saint Helena, Ascension, and Tristan da Cunha', 'רואנדה'),
('Romania', 'רומניה'),
('Russia', 'רוסיה'),
('Gaza Strip', 'רצועת עזה'),
('Sweden', 'שבדיה'),
('Switzerland', 'שווייץ'),
('Thailand', 'תאילנד'),
('Tunisia', 'תוניסיה'),
('Yemen', 'תימן')
